ZMS-567: LDAP attribute descriptions
Zimbra/adminguide pull request #10
Opened 2017-03-21 03:27 UTC by ilyusha

Descriptions of zimbraSSDBResourcePoolSize and zimbraSSDBResourcePoolTimeout.

2017-03-21 17:09 UTC, fatkudu commented on ssdb-configuration-options.adoc
> +wait for a resource before before throwing an exception. The default is 0,
s/before before/before/

2017-03-21 17:11 UTC, fatkudu requested changes
Good apart from minor typo.

2017-03-21 18:37 UTC, grishick approved these changes

2017-03-22 14:23 UTC, fatkudu approved these changes

2017-03-22 16:49 UTC, grishick approved these changes

2017-03-22 17:28 UTC, merged

2026-02-21 09:29 UTC, ghen2 commented on ssdb-configuration-options.adoc
> +to perform ephemeral data operations.
What is the unit of zimbraSSDBResourcePoolTimeout?  seconds or milliseconds?